apiVersion: v1
kind: Service
metadata:
  name: rollout-demo
  labels:
     app: rollout-demo
spec:
  ports:
  - nodePort: 32080
    port: 8080
    targetPort: http
    name: http
  selector:
    app: rollout-demo
  type: NodePort