kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: baseline-scan
spec:
  metrics:
  - name: baseline-scan
    provider:
      job:
        backoffLimit: 1
        spec:
          activeDeadlineSeconds: 1000
          template:
            spec:
              containers:
              - name: scan
                image: owasp/zap2docker-stable
                command: [zap-baseline.py,-t ,http://blue-green-app:8080/color]
              restartPolicy: Never
          backoffLimit: 0