apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: canary-simple
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: canary-simple
          servicePort: http
---
apiVersion: v1
data:
  allow-backend-server-header: "true"
  use-forwarded-headers: "true"
kind: ConfigMap
metadata:
  name: nginx-configuration
