apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blue-green
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: blue-app
          servicePort: 8080
---
apiVersion: v1
data:
  allow-backend-server-header: "true"
  use-forwarded-headers: "true"
kind: ConfigMap
metadata:
  name: nginx-configuration
